commandline: Fix -Werror={missing-declarations,suggest-attribute=noreturn}
../panel-plugin/commandline.c:40:6: error: no previous declaration for ‘sig_end_handler’ [-Werror=missing-declarations]
   40 | void sig_end_handler (int sig)
      |      ^~~~~~~~~~~~~~~
../panel-plugin/commandline.c: In function ‘sig_end_handler’:
../panel-plugin/commandline.c:40:6: error: function might be candidate for attribute ‘noreturn’ [-Werror=suggest-attribute=noreturn]
cc1: all warnings being treated as errors