Fix missing-prototypes
utils.c:38:15: error: no previous prototype for 'min_array' [-Werror=missing-prototypes]
utils.c:55:15: error: no previous prototype for 'max_array' [-Werror=missing-prototypes]
utils.c:73:7: error: no previous prototype for 'format_byte_humanreadable' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>