autotools-build: Explicitly require glib, gtk3, libxfce4util
libxfce4util is needed for e.g. xfce_get_license_text. Also for some
reasons the autotools distcheck fails with net.c:233:(.text+0x7eb):
undefined reference to `g_snprintf'.

autotools-build: Explicitly require libxfce4util

This is needed for e.g. xfce_get_license_text.